name: Node.js CI

on:
  push:
    branches:
      - master  # Set the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Change to your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=sonarintegration-1 
            -Dsonar.projectKey=sonarintegration-1_sonarscannodejs
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
      env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
